package weatherapi.model;

import lombok.Getter;

@Getter
public enum Condition {
    SUNNY(48),
    PARTLY_CLOUDY(47),
    CLOUDY(46),
    OVERCAST(45),
    MIST(44),
    PATCHY_RAIN_POSSIBLE(43),
    PATCHY_SNOW_POSSIBLE(42),
    PATCHY_SLEET_POSSIBLE(41),
    PATCHY_FREEZING_DRIZZLE_POSSIBLE(40),
    THUNDERY_OUTBREAKS_POSSIBLE(39),
    BLOWING_SNOW(38),
    BLIZZARD(37),
    FOG(36),
    FREEZING_FOG(35),
    PATCHY_LIGHT_DRIZZLE(34),
    LIGHT_DRIZZLE(33),
    FREEZING_DRIZZLE(32),
    HEAVY_FREEZING_DRIZZLE(31),
    PATCHY_LIGHT_RAIN(30),
    LIGHT_RAIN(29),
    MODERATE_RAIN_AT_TIMES(28),
    MODERATE_RAIN(27),
    HEAVY_RAIN_AT_TIMES(26),
    HEAVY_RAIN(25),
    LIGHT_FREEZING_RAIN(24),
    MODERATE_OR_HEAVY_FREEZING_RAIN(23),
    LIGHT_SLEET(22),
    MODERATE_OR_HEAVY_SLEET(21),
    PATCHY_LIGHT_SNOW(20),
    LIGHT_SNOW(19),
    PATCHY_MODERATE_SNOW(18),
    MODERATE_SNOW(17),
    PATCHY_HEAVY_SNOW(16),
    HEAVY_SNOW(15),
    ICE_PELLETS(14),
    LIGHT_RAIN_SHOWER(13),
    MODERATE_OR_HEAVY_RAIN_SHOWER(12),
    TORRENTIAL_RAIN_SHOWER(11),
    LIGHT_SLEET_SHOWERS(10),
    MODERATE_OR_HEAVY_SLEET_SHOWERS(9),
    LIGHT_SNOW_SHOWERS(8),
    MODERATE_OR_HEAVY_SNOW_SHOWERS(7),
    LIGHT_SHOWERS_OF_ICE_PELLETS(6),
    MODERATE_OR_HEAVY_SHOWERS_OF_ICE_PELLETS(5),
    PATCHY_LIGHT_RAIN_WITH_THUNDER(4),
    MODERATE_OR_HEAVY_RAIN_WITH_THUNDER(3),
    PATCHY_LIGHT_SNOW_WITH_THUNDER(2),
    MODERATE_OR_HEAVY_SNOW_WITH_THUNDER(1);

    private final int multiplier;

    Condition(int multiplier) {
        this.multiplier = multiplier;
    }
}
