/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api.models;

public class ForecastJsonResponseBuilder {
    //the instance to build
    private com.weatherapi.api.models.ForecastJsonResponse forecastJsonResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ForecastJsonResponseBuilder() {
        forecastJsonResponse = new com.weatherapi.api.models.ForecastJsonResponse();
    }

    public ForecastJsonResponseBuilder location(Location location) {
        forecastJsonResponse.setLocation(location);
        return this;
    }

    public ForecastJsonResponseBuilder current(Current current) {
        forecastJsonResponse.setCurrent(current);
        return this;
    }

    public ForecastJsonResponseBuilder forecast(Forecast forecast) {
        forecastJsonResponse.setForecast(forecast);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ForecastJsonResponse build() {
        return forecastJsonResponse;
    }
}